apiVersion: apps/v1
kind: #
metadata:
  name: #
  labels: 
    app: #
spec:
  replicas: 10
  selector:
    matchLabels:
      app: #
  template:
    metadata:
      labels:
        app: #
    spec:
      containers:
      - name: #
        image: #
        ports: 
        - containerPort: 5500
---
apiVersion: v1
kind: #
metadata:
  name: #
spec:
  type: #
  selector:
    app: #
  ports:
  - protocol: TCP
    port: 5500  
    targetPort: 5500