apiVersion: v1
kind: #
metadata:
  name: #
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen #;
        location / {
          proxy_pass http://#:#;
        }
      }
    }
---
apiVersion: apps/v1
kind: #
metadata:
  name: #
  labels:
    app: #
spec:
  replicas: 10
  selector:
    matchLabels:
      app: #
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: #
    spec:
      volumes:
      - name: #
        configMap:
          name: #
      containers:
      - name: #
        image: #
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: #
          mountPath: /etc/nginx/
---
apiVersion: v1
kind: #
metadata:
  name: #
spec:
  type: #
  selector:
    app: #
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80